# Generated by Django 6.0.2 on 2026-03-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caragral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abonadoid', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=90)),
                ('Lectura_anterior', models.IntegerField(default=0)),
                ('Lectura_actual', models.IntegerField(default=0)),
                ('Observacion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Caragral',
                'verbose_name_plural': 'caragral',
            },
        ),
    ]
