# Generated by Django 6.0.2 on 2026-02-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_caragral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caragral',
            name='Observacion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
