# Generated by Django 6.0.2 on 2026-02-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_caragral_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caragral',
            name='Observacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
