# Generated by Django 6.0.2 on 2026-03-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_caragral_observacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caragral',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
